Script started on 2015年03月10日 (週二) 20時24分55秒
]0;F74036386@2015cpp: ~/lab1F74036386@2015cpp:~/lab1$ whoi[Kami;pwd
F74036386
/home/F74036386/lab1
]0;F74036386@2015cpp: ~/lab1F74036386@2015cpp:~/lab1$ git config-l
git: 'config-l' is not a git command. See 'git --help'.
]0;F74036386@2015cpp: ~/lab1F74036386@2015cpp:~/lab1$ git config-l -l[C[C
user.email=F74036386@mail.ncku.edu.tw
user.name=F74036386
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/F74036386/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;F74036386@2015cpp: ~/lab1F74036386@2015cpp:~/lab1$ git clone https://github.com/<your github account>/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gitf/lab1.git[1P/lab1.gitF/lab1.git7/lab1.git4/lab1.git0/lab1.git3/lab1.git6/lab1.git3/lab1.git8/lab1.git6/lab1.git[C[C[C[C[C[C[C[C[C
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74036386@2015cpp: ~/lab1F74036386@2015cpp:~/lab1$ exit

Script done on 2015年03月10日 (週二) 20時26分40秒
